---
title: "demo_data_analysis"
format: html
editor: visual
---

```{r}
# Set up

rm(list = ls(all = TRUE))

# Load packages
packages <- c("ggplot2", "dplyr", "tidyr", "kableExtra", "gmodels", "lme4", "sjPlot")
#install.packages(packages)
lapply(packages, library, character.only = TRUE)

# define paths
demo_path <- "C:/Users/musialm/OneDrive - Charité - Universitätsmedizin Berlin/PhD/04_B01/WP3/WP3_DATA/PILOT_3/demo_data"

# read dfs
load(file.path(demo_path, "demo_psych_data.RData"))
```

# Age

```{r}
age_df <- demo_psych_df %>%
  summarise(mean = mean(age),
            se_correct = sd(age, na.rm = TRUE)/sqrt(n()),
            ci_l = ci(age, na.rm=TRUE)[2],
            ci_u = ci(age, na.rm=TRUE)[3],
            n = n())

age_df %>%
  kable("html") %>%
  kable_styling(font_size = 14,
                latex_options = "scale_down")
```

```{r}
ggplot(demo_psych_df, aes(x=age)) +
  geom_bar(fill = "lightblue") +
  theme_light()
```

# Sex

```{r}
sex_df <- demo_psych_df %>%
  group_by(sex) %>%
  summarise(n = n())

sex_df %>%
  kable("html") %>%
  kable_styling(font_size = 14,
                latex_options = "scale_down")
```

# AUD criteria

```{r}
aud_df <- demo_psych_df %>%
  group_by(aud_sum) %>%
  summarise(n = n())

aud_df %>%
  kable("html") %>%
  kable_styling(font_size = 14,
                latex_options = "scale_down")
```

```{r}
ggplot(demo_psych_df, aes(x=aud_sum)) +
  geom_bar(fill = "lightblue") +
  theme_light()
```

# AUDIT score

```{r}
audit_df <- demo_psych_df %>%
  summarise(mean = mean(audit_sum),
            se_correct = sd(audit_sum, na.rm = TRUE)/sqrt(n()),
            ci_l = ci(audit_sum, na.rm=TRUE)[2],
            ci_u = ci(audit_sum, na.rm=TRUE)[3],
            n = n())

audit_df %>%
  kable("html") %>%
  kable_styling(font_size = 14,
                latex_options = "scale_down")
```

```{r}
ggplot(demo_psych_df, aes(x=audit_sum)) +
  geom_bar(fill = "lightblue") +
  theme_light()
```
